SessionAndStateMgmt/Models/CommentForm.cs
using System.ComponentModel.DataAnnotations;

namespace SessionAndStateMgmt.Models
{
    public class CommentForm
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public string Comment { get; set; }
    }
}

SessionAndStateMgmt/Models/ErrorViewModel.cs
namespace SessionAndStateMgmt.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SessionAndStateMgmt/Controllers/CookieController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace SessionAndStateMgmt.Controllers
{
    public class CookieController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, Guid.NewGuid().ToString()),
                new Claim(ClaimTypes.Name, "Alvin"),
                new Claim(ClaimTypes.MobilePhone, "1234567890"),
                new Claim(ClaimTypes.Email, "nV9oJ@example.com"),
                new Claim(ClaimTypes.Role, "Admin")
            };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

            return View();
        }

        public IActionResult Secret()
        {
            var user = HttpContext.User;

            var result = new
            {
                Id = user.FindFirst(ClaimTypes.NameIdentifier)?.Value,
                Name = user.FindFirst(ClaimTypes.Name)?.Value,
                Phone = user.FindFirst(ClaimTypes.MobilePhone)?.Value,
                Email = user.FindFirst(ClaimTypes.Email)?.Value,
                Role = user.FindFirst(ClaimTypes.Role)?.Value
            };

            return View(result);
        }
    }
}

SessionAndStateMgmt/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SessionAndStateMgmt.Models;
using System.Diagnostics;

namespace SessionAndStateMgmt.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SessionAndStateMgmt/Controllers/SessionController.cs
using Microsoft.AspNetCore.Mvc;

namespace SessionAndStateMgmt.Controllers
{
    public class SessionController : Controller
    {
        public const string SessionKeyName = "_Name";
        public const string SessionKeyAge = "_Age";

        public IActionResult Index()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString(SessionKeyName)))
            {
                HttpContext.Session.SetString(SessionKeyName, "Alvin");
                HttpContext.Session.SetInt32(SessionKeyAge, 27);
            }

            var name = HttpContext.Session.GetString(SessionKeyName);
            var age = HttpContext.Session.GetInt32(SessionKeyAge).ToString();


            return View(model: new { Name = name, Age = age });
        }

        public IActionResult Secret()
        {
            var name = HttpContext.Session.GetString(SessionKeyName);
            var age = HttpContext.Session.GetInt32(SessionKeyAge).ToString();

            return View(model: new { Name = name, Age = age });
        }
    }
}

SessionAndStateMgmt/Controllers/TempDataController.cs
using Microsoft.AspNetCore.Mvc;
using SessionAndStateMgmt.Models;

namespace SessionAndStateMgmt.Controllers
{
    public class TempDataController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(CommentForm request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            TempData["SuccessMsg"] = "Form submitted successfully";

            ModelState.Clear();

            return RedirectToAction(nameof(Index));
        }
    }
}

SessionAndStateMgmt/Views/Cookie/Index.cshtml
<h1 class="text-success">Cookie Activated</h1>

<p>I will be expiring when idle for 1 minute ...</p>

SessionAndStateMgmt/Views/Cookie/Secret.cshtml
@if (Model != null && Model?.Id != null)
{
    <h1 class="text-success">Cookie is activated now @Model</h1>

    <p>I will be expiring in 1 minute...</p>
}
else
{
    <h1 class="text-danger">Cookie is not activated</h1>

    <p>Click cookie link first</p>
}

SessionAndStateMgmt/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SessionAndStateMgmt/Views/Session/Index.cshtml
<h1 class="text-success">Session Activated</h1>

<p>I will be expiring in 1 minute...</p>

SessionAndStateMgmt/Views/Session/Secret.cshtml
@if(Model != null && Model?.Name != null)
{
    <h1 class="text-success">Session is activated now @Model</h1>

    <p>I will be expiring when idle for 1 minute ...</p>
}
else
{
    <h1 class="text-danger">Session is not activated</h1>

    <p>Click session link first</p>
}

SessionAndStateMgmt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SessionAndStateMgmt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SessionAndStateMgmt.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SessionAndStateMgmt</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cookie" asp-action="Index">Cookie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cookie" asp-action="Secret">Activate Cookie First</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Session" asp-action="Index">Session</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Session" asp-action="Secret">Activate Session First</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TempData" asp-action="Index">Temp Data</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SessionAndStateMgmt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SessionAndStateMgmt/Views/TempData/Index.cshtml
@model CommentForm


<form method="POST" class="mb-5">
    <div class="mb-3">
        <label class="form-label">Name</label>
        <input asp-for="Name" type="text" class="form-control">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label class="form-label">Comment</label>
        <textarea asp-for="Comment" class="form-control" rows="3"></textarea>
        <span asp-validation-for="Comment" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@{
    if (TempData["SuccessMsg"] != null)
    {
        <div class="alert alert-success" role="alert">
            <p>@TempData["SuccessMsg"]</p>
        </div>
    }


    // if (TempData.Peek("SuccessMsg") != null)
    // {
    //     <div class="alert alert-success" role="alert">
    //         <p>@TempData.Peek("SuccessMsg")</p>
    //     </div>
    // }

    // TempData.Keep("SuccessMsg");
}

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}